### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by enthus1ast** [guzba/crunchy#1]
Hi Guzba,

i've benchmarked the sha256 agains 
nimcrypto and the openssl implementation:

```nim
import crunchy, benchy, strutils

let data = "The quick brown fox jumps over the lazy dog".repeat(10_000_000)
echo data.len.formatSize()

timeIt "crunchy sha256":
  keep crunchy.sha256(data)


import nimcrypto
timeIt "nimcrypto sha256":
  keep nimcrypto.sha256.digest(data)


import strutils

const SHA256Len = 32

proc SHA256(d: cstring, n: culong, md: cstring = nil): cstring {.cdecl, importc.}
proc SHA256(s: string): string =
  result = ""
  let s = SHA256(s.cstring, s.len.culong)
  for i in 0 ..< SHA256Len:
    result.add s[i].BiggestInt.toHex(2).toLower

timeIt "openssl sha256":
  keep SHA256(data)
```

i compile with:

```
nim c -d:ssl --passl:-lcrypto --passl:-lssl -d:release -d:allowSimd  --gc:arc --opt:speed -d:lto -r "c:\Users\david\projects\nimPlayground\crunchyt.nim"
```

```
410.08MiB
name ............................... min time      avg time    std dv   runs
crunchy sha256 .................. 2119.437 ms   2190.603 ms  ±110.765     x3
nimcrypto sha256 ................ 1885.133 ms   1886.219 ms    ±1.623     x3
openssl sha256 ................... 958.929 ms    973.808 ms   ±14.016     x6
```

My cpu:

```
# Get-WmiObject -Class Win32_Processor -ComputerName. | Select-Object -Property [a-z]*
Name                                    : Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
NumberOfCores                           : 4
NumberOfEnabledCore                     : 4
NumberOfLogicalProcessors               : 8                    
```

**Comment by enthus1ast** [comment]
Is it possible that i've not enabled SIMD correctly?

**Comment by treeform** [comment]
The number of runs you have is very small x3, x3, and x6. I would recommend setting a fixed number of runs (`timeIt "crunchy sha256", 100:`) or making your data smaller (`.repeat(100_000)`). The openssl will probalby still be faster but numbers will be more accurate.

**Comment by guzba** [comment]
The sha256 implementation currently copies the entire data blob before processing which is not going to be as fast as possible. The copying also not strictly needed, but keeps things simpler at first. Still far faster than non-accelerated version, however OpenSSL is for sure going to have both SIMD and copy-avoiding since it is far more mature.

I only use sha256 for small things right now so it hasn't mattered. Someday I'll make it better as I have for crc32 and adler32.

**Comment by guzba** [comment]
It is also possible your CPU does not support the SHA hardware instructions so they are not being used. Could try with and without -d:crunchyNoSimd to see if behavior changes or not.

**Comment by guzba** [comment]
On my PC with slightly tweaked values I get

```
   min time    avg time  std dv   runs  name
  22.448 ms   22.863 ms  ±0.374   x218  crunchy sha256
 111.697 ms  111.915 ms  ±0.374    x45  nimcrypto sha256
 ```


```nim
import crunchy, benchy, strutils

let data = "The quick brown fox jumps over the lazy dog".repeat(1_000_000)
echo data.len.formatSize()

timeIt "crunchy sha256":
  keep crunchy.sha256(data)


import nimcrypto
timeIt "nimcrypto sha256":
  keep nimcrypto.sha256.digest(data)
```

**Comment by enthus1ast** [comment]
Interestingly with and without `-d:crunchyNoSimd` makes no difference (on this notebook cpu)

**Comment by guzba** [comment]
SHA instructions are only on newer CPUs, from https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam under Settings its about 47% of consumer CPUs. Introduced in 2013 https://en.wikipedia.org/wiki/Intel_SHA_extensions so kind of slow to get out there.
